spring.application.name=book-service

# Rastgele Port (Dinamik Scale-Out)
server.port=0

# H2 & JPA Ayarlari
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.jpa.database=h2
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Eureka Kayit Ayarlari
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}:${server.port}
eureka.client.service-url.default-zone=${EUREKA_URI:http://localhost:8761/eureka}

# Actuator & Prometheus Ayarlari
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

# OpenTelemetry & Tracing Ayarlari (%100 Sampling)
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

# Loglarda TraceId ve SpanId Gösterimi (Loki ve Konsol Takibi icin)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]