spring.application.name=user-service
server.port=8082

# Eureka Server Kayit Ayarlari
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Email içindeki @ (%40) ve özel karakterlerin URL'de hata vermesini engelleyen ayar:
server.tomcat.uri-encoding=UTF-8
server.max-http-request-header-size=65536

# Observability ve Log Korelasyon Ayarlar?
management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://127.0.0.1:4318/v1/traces}
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]